name: gotherepy_doctor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts:
  country_picker:
  loader_overlay:
  flutter_spinkit: ^5.2.0
  pin_code_fields: 7.4.0
  image_picker: 0.8.7+4
  banner_carousel: 1.2.1
  get_storage:
  fluttertoast:
  agora_rtc_engine: ^6.2.0
  permission_handler: 10.2.0
#  firebase_core:
#  firebase_auth:
#  firebase_messaging:
#  flutter_local_notifications:
  carousel_slider: 4.1.1
  percent_indicator:

  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash_and_intro_screen_images/
    - assets/splash_and_intro_screen_images/plant.png
    - assets/auth_images/
    - assets/drawer_icons/
    - assets/counseling/Individual_counseling/
    - assets/counseling/Individual_counseling/Marriage.png
    - assets/home_screen_images/activities_images/
    - assets/home_screen_images/appBar_popupMenu_icons/
    - assets/meditation_images/
    - assets/meditation_images/feelings_moods_images/
    - assets/miscellaneous_images/
    - assets/new_logo.PNG


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/new_logo.PNG"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/new_logo.PNG"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/new_logo.PNG"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/new_logo.PNG"